### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by haribole** [wso2/docker-apim#104]
**Description:**

Unable to pull docker image

docker: Error response from daemon: pull access denied for docker.wso2.com/wso2am, repository does not exist or may require 'docker login'.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2am

**OS, DB, other environment details and versions:**    
Linux

**Steps to reproduce:**
login using "docker login docker.wso2.com
docker run -it docker.wso2.com

**Related Issues:**

**Comment by ThilinaManamgoda** [comment]
@haribole In order to run WSO2 API Manager Docker container, you have to use the following command,
`docker run -it \
-p 9443:9443 \
-p 8243:8243 \
-p 8280:8280 \
docker.wso2.com/wso2am`
also, have you subscribed to our Free Trial [Subscription](https://wso2.com/free-trial-subscription)? or do you have a Production subscription for WSO2 API Manager?. Just by registering to wso2.com web site you won't be able to pull these images.

**Comment by DilanUA** [comment]
@haribole Are you still affected by this issue ?

**Comment by msasikumar** [comment]
I have the same issue.

 docker login https://docker.wso2.com             
Username (msasikumar@gmail.com): msasikumar@ gmail.com
Password:
Login Succeeded

$ docker pull docker.wso2.com/wso2am
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2am, repository does not exist or may require 'docker login'

**Comment by msasikumar** [comment]
Never mind...My trial subscription was expired which caused the error.

**Comment by thomasfranz** [comment]
I have an issue with missing access-rights as well.
`docker pull docker.wso2.com/wso2am:2.2.0
Error response from daemon: Get https://docker.wso2.com/v2/wso2am/manifests/2.2.0: unauthorized: authentication required`
I have subscribed for the free trial, but my credentials are not accepted:
`docker login https://docker.wso2.com`
results in
``Error saving credentials: error storing credentials - err: exit status 1, out: The user name or passphrase you entered is not correct.``

**Comment by awsdevopro** [comment]
I was facing same issue ```ERROR: pull access denied for wso2am-analytics, repository does not exist or may require 'docker login'```
It should be ```docker login https://docker.wso2.com```
and then use the credential you used to subscribe their website. Hope it will work.

**Comment by GJRTimmer** [comment]
I have the same problem.
I have a trial account.

I can successfully login however still getting access denied.
Email adres: gert-jan.timmer@vanadgroup.com

Logging
```bash
gtimmer@Aeris:~$ docker login https://docker.wso2.com
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/gtimmer/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
gtimmer@Aeris:~$ docker run -it -p 9443:9443 docker.wso2.com/wso2is
Unable to find image 'docker.wso2.com/wso2is:latest' locally
docker: Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'.
See 'docker run --help'.
gtimmer@Aeris:~$ docker pull docker.wso2.com/wso2is
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
gtimmer@Aeris:~$ docker login https://docker.wso2.com
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/gtimmer/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
gtimmer@Aeris:~$ docker pull docker.wso2.com/wso2is
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
gtimmer@Aeris:~$ docker logout
Not logged in to https://index.docker.io/v1/
gtimmer@Aeris:~$ docker logout docker.wso2.com
Removing login credentials for docker.wso2.com
gtimmer@Aeris:~$ docker login docker.wso2.com
Username: gert-jan.timmer@vanadgroup.com
Password: 
WARNING! Your password will be stored unencrypted in /home/gtimmer/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
gtimmer@Aeris:~$ docker pull docker.wso2.com/wso2is
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
gtimmer@Aeris:~$ docker pull docker.wso2.com/wso2is:2.5.0
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
gtimmer@Aeris:~$ docker login https://docker.wso2.com
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/gtimmer/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
gtimmer@Aeris:~$ docker pull docker.wso2.com/wso2is:2.5.0
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
gtimmer@Aeris:~$
```

I also tried the solution from @awsdevopro including a `docker logout docker docker.wso2.com` still no success.

Please advice.

**Comment by GJRTimmer** [comment]
Docker engine Information:

```bash
gtimmer@Aeris:~$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by ThilinaManamgoda** [comment]
We have checked your email address in our system and we could not find the Free trial subscription for the particular email address. If you don't mind, could you please create a Free trial account[1] using this email address. 

[1] https://wso2.com/subscription/free-trial

**Comment by GJRTimmer** [comment]
Thanks. apparently this was different then the account I had setup. Thank you. pulling works now.

**Comment by praddy4** [comment]
praddy@blrevp482d nodejsapp $ docker login docker.wso2.com
Username (pradeep_ln@edgeverve.com): 
Password: 
Login Succeeded
praddy@blrevp482d nodejsapp $ docker pull docker.wso2.com/wso2am
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2am, repository does not exist or may require 'docker login'
praddy@blrevp482d nodejsapp $ docker run -it \
> -p 9443:9443 \
> -p 8243:8243 \
> -p 8280:8280 \
> docker.wso2.com/wso2am
Unable to find image 'docker.wso2.com/wso2am:latest' locally
docker: Error response from daemon: pull access denied for docker.wso2.com/wso2am, repository does not exist or may require 'docker login'.
See 'docker run --help'.

Not able to pull image despite registering and successfully logged into docker registry.
Can you please help

**Comment by ThilinaManamgoda** [comment]
@praddy4 Did you register for [Free trial subscription](https://wso2.com/subscription/free-trial )?

**Comment by franscal7** [comment]
Me too

```
PS C:\> docker login https://docker.wso2.com
Authenticating with existing credentials...
Login Succeeded
PS C:\> docker pull docker.wso2.com/wso2is
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2is, repository does not exist or may require 'docker login'
PS C:\>
```

**Comment by franscal7** [comment]
A subscription of WSO2 is required and my trial has expired

https://github.com/wso2/docker-ei/issues/84#issuecomment-408794366

**Comment by ThilinaManamgoda** [comment]
@fmoralvi Could you please let us know your email address used for the Docker login?

**Comment by fmoralvi** [comment]
> @fmoralvi Could you please let us know your email address used for the Docker login?

I am using the email fmoralvi@gmail.com and fmoralvi@isban.com

**Comment by ThilinaManamgoda** [comment]
@fmoralvi Which one did you use to create the Trial account?

**Comment by fmoralvi** [comment]
> @fmoralvi Which one did you use to create the Trial account?

both emails

**Comment by ThilinaManamgoda** [comment]
@fmoralvi  I cannot see any subscriptions for both emails. Did you create both accounts using this form https://wso2.com/subscription/free-trial ?

**Comment by fmoralvi** [comment]
> @fmoralvi I cannot see any subscriptions for both emails. Did you create both accounts using this form https://wso2.com/subscription/free-trial ?

I have created a account using this url: https://wso2.com/user/register 
Is the same?

**Comment by ThilinaManamgoda** [comment]
@fmoralvi It is not the same. A free trial subscription is not attached when you create an account using the URL https://wso2.com/user/register. Please create an account using the URL https://wso2.com/subscription/free-trial.

**Comment by fmoralvi** [comment]
> @fmoralvi It is not the same. A free trial subscription is not attached when you create an account using the URL https://wso2.com/user/register. Please create an account using the URL https://wso2.com/subscription/free-trial.

thank you very much for your help.
I think, the procedure is not very clear

**Comment by valdon82** [comment]
Hi, i can't pull docker image... i have created an account using the free subscription link but i cannot pull docker image.
email used: v.donnarumma@reply.eu

**Comment by ThilinaManamgoda** [comment]
@valdon82 Sorry for the late response. We are looking into the issue and will provide an update as soon as possible.

**Comment by ThilinaManamgoda** [comment]
@valdon82 There was an issue with creating Free trial subscription and now it is fixed. We have reset your password and sent you the new credentials in a private email. Please use those credentials and set up a new password and retry pulling WSO2 docker images.

**Comment by nick-uk** [comment]
Using https://wso2.com/subscription/free-trial to enable my trial, when I'm clicking on submit, the field validator prints the message "Please enter a corporate email" but the email field is not editable!

**Comment by ThilinaManamgoda** [comment]
@valdon82 Were you able to try out the sugessted approach?
@nick-uk Could you please mention the OS, browser and browser version used when you faced the issue.

**Comment by abdelbassit** [comment]
I have the same problem, I can't login to docker.wso2.com.

I have a free trial account.

I can access to website with my email and password, but I can't login to docker.wso2.com.
#docker login docker.wso2.com
Username: abdel.bouchakri@gmail.com

Error saving credentials: error storing credentials - err: exit status 1, out: `Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached`

**Comment by valdon82** [comment]
> @valdon82 Were you able to try out the sugessted approach?

I have used new credentials but it does not work :(
_"Unable to find image 'docker.wso2.com/wso2ei-integrator:latest' locally
docker: Error response from daemon: pull access denied for docker.wso2.com/wso2ei-integrator, repository does not exist or may require 'docker login'."_

The login command is success ("Login Succeeded").

Any

**Comment by ThilinaManamgoda** [comment]
@abdelbassit I'll check this and get back to you.
@valdon82 when did you try this?.

**Comment by valdon82** [comment]
> @valdon82 when did you try this?.
Now

**Comment by ThilinaManamgoda** [comment]
@valdon82 Your trial account is only valid for 15 days. Now it is expired, that's why you cannot pull images.

**Comment by abdelbassit** [comment]
@ThilinaManamgoda Any update about my problem access to your docker registry?

**Comment by ThilinaManamgoda** [comment]
@abdelbassit Apologies for the late reply. In order to create a free trial account, you need a corporate email account.

**Comment by abdelbassit** [comment]
@ThilinaManamgoda  I have another account with a corporate email, and I have the same problem.

**Comment by ThilinaManamgoda** [comment]
@abdelbassit could you please mention your corporate email?

**Comment by abdelbassit** [comment]
abdel@credimarket.com

**Comment by mtsilva** [comment]
Hi @ThilinaManamgoda I'm facing the same problem, my email is mauricio.trindade@farfetch.com. Can you check it, please?

**Comment by alozie-michael** [comment]
I was unable to pull the wso2 image, so i logged out and when i tried to login again, i get the below error.

```
michaelalozie-> docker login docker.wso2.com
Username: michael.alozie@trium.ng
Password: 
Error response from daemon: Get https://docker.wso2.com/v2/: unauthorized: authentication required
```

Please help

**Comment by alozie-michael** [comment]
I have been able to login, i also have a free atrium active, but i can't pull the docker image. See below.

```
michaelalozie-> docker pull docker.wso2.com/wso2am
Using default tag: latest
Error response from daemon: pull access denied for docker.wso2.com/wso2am, repository does not exist or may require 'docker login'
```
Please help.

**Comment by alozie-michael** [comment]
![Screenshot 2020-04-22 at 11 03 31 PM](https://user-images.githubusercontent.com/25454365/80038425-8adbd600-84ed-11ea-9140-beb052aef402.png)

**Comment by ThilinaManamgoda** [comment]
@alozie-michael We are looking into the issue. We will update you shortly.

**Comment by ThilinaManamgoda** [comment]
@alozie-michael Could you please try to pull the image now.

**Comment by chirangaalwis** [comment]
Hi everyone,

WSO2 recommends you to use WSO2 support service (see [Subscription details](https://wso2.com/subscription/)) for this type of queries.

Thus, closing this issue.

**Comment by ArmanAndalibKhah** [comment]
> @fmoralvi It is not the same. A free trial subscription is not attached when you create an account using the URL https://wso2.com/user/register. Please create an account using the URL https://wso2.com/subscription/free-trial.
 
Hi, I have a similar problem. I registered on the site but I can not find the subscription section in the link (https://wso2.com/subscription/free-trial) you sent. Thank you very much for your help.
my email: arman.andalib.work1400@gmail.com
