### ISSUE TITLE
stats_db.API_REQUEST_SUMMARY not being created on startup

### ISSUE THREAD

**Issue by simontrimboy** [wso2/docker-apim#111]
**Description:**
The stats_db summary table/s are not being created immediately on startup; resulting in the following exception when trying to access API analytics.

```
ERROR - APIUsageStatisticsRdbmsClientImpl Error occurred while checking existence of the table:API_REQUEST_SUMMARY
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'stats_db.API_REQUEST_SUMMARY' doesn't exist
```

I have noticed the issue can be resolved by adding an additional docker compose link from the api-manager service to mysql.

```
version: '2.3'
...
  api-manager:
  ...
    links:
      - mysql
```

**Comment by DilanUA** [comment]
@simontrimboy Thanks for reporting. We are currently looking into this. Will reply to you shortly.
