### ISSUE TITLE
Can you provide a reverse proxy compose example which works for Log Analyzer gadgets?

### ISSUE THREAD

**Issue by simontrimboy** [wso2/docker-apim#115]
**Description:**
It would be useful to see an example with NGINX for the simple patterns covered here. In particular I have noticed rendering the shindig gadgets for the "log analyzer" (live log viewer etc..) fails to connect when behind a reverse proxy.

So this request works for example :

`https://am.dev.wso2.com:9443/admin/loganalyzer/live-log-viewer
`

but this doesn't - the **gadgets** fail to load onto the page/s

`https://am.dev.proxy.com/admin/loganalyzer/live-log-viewer
`

Indeed the proxy request results in the error below in the carbon logs

```
BasicHttpFetcher The following exception occurred when fetching https://am.dev.wso2.com/portal/store/carbon.super/fs/gadget/LiveLogViewer/index.xml: 4 ms elapsed.
java.net.ConnectException: Connection refused (Connection refused)
```

**Steps to reproduce:**

- I have changed the hostname from default config and updated JKS to "am.dev.wso2.com" 
- I have created SSL certs with hostname "am.dev.proxy.com" and copied to /etc/nginx/ssl
- Here is my example NGINX conf:

```
upstream am.dev.wso2.com {
    server api-manager:9443;
    ip_hash;
}
```

```
server {
    listen 443;
    server_name am.dev.proxy.com;
    proxy_set_header X-Forwarded-Port 443;
    ssl on;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_read_timeout 5m;
        proxy_send_timeout 5m;
        proxy_pass https://am.dev.wso2.com;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by DilanUA** [comment]
@simontrimboy I think this issue is also in relevance to https://github.com/wso2/docker-apim/issues/108.
Will reach to you shortly.

**Comment by simontrimboy** [comment]
Apparently **shindig** uses the **server port** to render not the proxy port.

To honour this I have updated **index.js** in

/home/wso2carbon/wso2am-2.1.0/repository/deployment/server/jaggeryapps/portal/extensions/components/gadget

to hard set the port used in deriving **resolveGadgetURL**

```
    var resolveGadgetURL = function (uri) {
        uri = resolveURI(uri);
        if (uri.match(/^https?:\/\//i)) {
            return uri;
        }
        uri = uri.replace(/^(..\/)*/i, '');

        var hostname = host.hostname ? host.hostname : window.location.hostname,
            //port = host.port ? host.port : window.location.port,
            port = "9443",
            protocol = host.protocol ? (host.protocol + ":") : window.location.protocol;

        //port = port ? (":" + port) : "";
        port = ":" + port;
        return protocol + '//' + hostname + port + context + '/' + uri;
    };
```

So far I cannot see another way around this; I suspect there may be a solution at the load balancer layer?

**Comment by simontrimboy** [comment]
Feature now deprecated v2.2.0 onwards
