### ISSUE TITLE
APIM fails to start in when running docker-compose for APIM-ISasKM-with-Analytics

### ISSUE THREAD

**Issue by chewbyte** [wso2/docker-apim#132]
Out of the box docker-compose for APIM-ISasKM-with-Analytics. I raised the health check interval and the timeouts. Mysql, IS-as-KM and the Analytics container start fine. The APIM manager container stops and the output is:

```
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 16: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 32: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 35: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 36: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 37: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 38: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 39: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: : not found
api-manager_1   | /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: 40: /home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh: Syntax error: word unexpected (expecting "in")
apim-isaskm-with-analytics_api-manager_1 exited with code 2
```

I'm using Docker for Windows.

**Comment by chewbyte** [comment]
Figured it out. Convered the following file:
`docker-compose\APIM-ISasKM-with-Analytics\apim\bin\wso2server.sh`
to UNIX (LF) line endings from Windows (CR LF) and all containers started fine.

**Comment by wangdh1** [comment]
this api-manager service stops and the also output is:
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 16: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 32: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 35: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 36: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 37: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 38: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
: not foundarbon/wso2am-2.6.0/bin/wso2server.sh: 39: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 
/home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: 40: /home/wso2carbon/wso2am-2.6.0/bin/wso2server.sh: Syntax error: word unexpected (expecting "in")
