### ISSUE TITLE
Error in docker-compose pull

### ISSUE THREAD

**Issue by cvillami** [wso2/docker-apim#171]
I want to evaluate some capabilities of wso2 in docker, but it always gives error, someone can help me.

**cvillami$** docker login docker.wso2.com
      Username: chr_villamizar@yahoo.es
      Password: 
      Login Succeeded
**cvillami$** docker-compose pull
      Pulling mysql (mysql:5.7.19)...
      5.7.19: Pulling from library/mysql
      Digest: sha256:bfb22e93ee87c6aab6c1c9a4e7cdc68e9cb9b64920f28fa289f9ffae9fe8e173
      Status: Image is up to date for mysql:5.7.19
      Pulling am-analytics (docker.wso2.com/wso2am-analytics:2.5.0)...
      ERROR: pull access denied for docker.wso2.com/wso2am-analytics, repository does not exist or may require 'docker login'

**Comment by ThilinaManamgoda** [comment]
@cvillami In order to pull docker images from docker.wso2.com you must have a free trial subscription. Please subscribe for a trial account here https://wso2.com/subscription/free-trial.

**Comment by chirangaalwis** [comment]
@cvillami are you still facing this issue?

**Comment by cvillami** [comment]
> @cvillami are you still facing this issue?

Thanks for answering, I have already solved the problems.

**Comment by chirangaalwis** [comment]
Closing the issue since the defined problem is solved.
