### ISSUE TITLE
MOTD as an Arg

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-apim#173]
**Description:**
Currently, we manually change the MOTD message for GA and WUM updated builds because the  MOTD message is hardcoded. It would be much easier if we can pass this as an ARG on build time.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-apim/pull/174.

**Comment by DilanUA** [comment]
Closed based on above merge.
