### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/home/wso2carbon/init.sh\": permission denied": unknown.

### ISSUE THREAD

**Issue by ScripDid** [wso2/docker-apim#189]
**Description:** Error when running the container on Ubuntu

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:** Follow build instructions

**Related Issues:** docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/home/wso2carbon/init.sh\": permission denied": unknown.

**Comment by ScripDid** [comment]
File permissions were the issue

**Comment by xmysg** [comment]
I also encountered this problem when deploying the go binary. How did you solve it?

**Comment by xmysg** [comment]
My email address is lm201881@gmail.com, please send me an email.
