### ISSUE TITLE
Profile optimization commands are not working on 2.6.0.x and above

### ISSUE THREAD

**Issue by athiththan11** [wso2/docker-apim#250]
**Description:**
The following profile optimization commands are not working on APIM Docker images 2.6.0.6 and above

```shell
docker run -ti <> --optimize -Dprofile=api-publisher
```

These commands were working fine and able to observe related profile optimization logs at the server startup in older releases (2.6.0.4 & 2.6.0.5)

**Affected Product Version:**

- 2.6.0.6 and above   

**Steps to reproduce:**

- Clone or download the release from [here](https://github.com/wso2/docker-apim/releases) and build the image locally
- Execute the following Docker run command along with profile optimization flags and arguments

```shell
docker run -it -p 8280:8280 -p 8243:8243 -p 9443:9443 --name apim-docker wso2am:2.6.0.6 --optimize -Dprofile=api-publisher
```
The WSO2 API-M server gets started without any profile optimization executions.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-apim/pull/253.
