### ISSUE TITLE
change the ip of the container by the ip of the host in the store

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-apim#267]
**Description:**
Hello, I want to change the nex ip (container ip) by host ip. How I can do that?
![image](https://user-images.githubusercontent.com/1907656/69587108-a2e91100-0fb2-11ea-96e2-70f1186a70da.png)

My goal is to invoke the endpoint using the api console in the apimanager store, but I get the next curl that have the container ip
![image](https://user-images.githubusercontent.com/1907656/69587370-65d14e80-0fb3-11ea-8a6e-ba138beb0401.png)

**Step to reproducie**
1. cd docker-apim\docker-compose\apim-with-analytics
1. docker-compose up -d
1. Create an api and application
1. Go to store to subscribe, next clic the api console tab to invoke an endpoint in the api
1. Get the curl to invoke the endpoint with the ip of the container.

**Comment by chirangaalwis** [comment]
@oscarvesga since this is a query regarding API Manager's configurations, transferring this issue to API Manager product repository.

**Comment by oscarvesga** [comment]
@chirangaalwis this is the same issue and it's solution https://github.com/wso2/product-apim/issues/5447
