### ISSUE TITLE
[3.2.0] Evaluate Adding the Docker Source Git Release Tag Version to Image Metadata

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/docker-apim#338]
**Description:**
Currently, the Docker source Git release tag version is included as part of the Docker image tag (see [image tagging mechanism](https://medium.com/faun/wso2-products-dockerized-image-tagging-mechanism-9b4499831548)).

Moving forward in order to avoid complexities within the used image tags and improve their clarity, it needs to be evaluated if this value can be added as metadata of the image (using [Docker image LABELS](https://docs.docker.com/engine/reference/builder/#label)).

**Sub Tasks:**
- [x] Add source label in Alpine based Docker resources
- [x] Add source label in CentOS based Docker resources
- [x] Add source label in Ubuntu based Docker resources
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
As per evaluation, it was discovered that predefined `LABEL` schemas are already available. Please see some of the following schema types.

- [OCI based label schema](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys)
- [Label schema](http://label-schema.org/rc1/) - An informative article on the importance of using image metadata can be found from [here](https://medium.com/@chamilad/lets-make-your-docker-image-better-than-90-of-existing-ones-8b1e5de950d).

Else, we have to formulate a WSO2 specific metadata mechanism since, we will most probably be using one or two `LABEL` types mapping to our requirements.

@ThilinaManamgoda @DilanUA @rasanjaya85 @msmshariq WDYT?

**Comment by ThilinaManamgoda** [comment]
@chirangaalwis In the **OCI based label schema**, we can use the annotation **org.opencontainers.image.source** for pointing the Dockerfile source right?. Is there information that we need to cover which is not available in the given predefined label schemas.

**Comment by chirangaalwis** [comment]
Moving this task to a new milestone as the release of Docker images needs to be addressed immediately.

**Comment by chirangaalwis** [comment]
For this purpose, custom, WSO2 specific Dockerfile `LABEL` with key `com.wso2.docker.source` was introduced.
