### ISSUE TITLE
[3.2.0] docker-compose must be updated because MySQL JDBC Driver is no longer in the Docker image

### ISSUE THREAD

**Issue by david-maumenee** [wso2/docker-apim#344]
**Description:**
Since MySQL JDBC Driver is no longer in the Docker image https://github.com/wso2/docker-apim/pull/342/commits/0e7f745c029375c4c0413c51d14e11f4a01901fc docker-compose file and README must be updated to provide this driver from a volume

**Comment by chirangaalwis** [comment]
@david-maumenee we package the MySQL JDBC driver within the temporary, custom Docker image built with the official Docker image of the relevant WSO2 product profile, as the base in the Docker Compose deployments (refer to the official [documentation](https://docs.docker.com/compose/gettingstarted/#step-4-build-and-run-your-app-with-compose) on how custom image Dockerfiles can be defined in Docker Compose).

The following is a sample of the custom Dockerfile we have created for API Manager All-In-One in Docker Compose deployments.

```
# set base Docker image to WSO2 API Manager Docker image with latest WSO2 Updates
FROM docker.wso2.com/wso2am:3.2.0
LABEL maintainer="WSO2 Docker Maintainers <dev@wso2.org>"

# build arguments for external artifacts
ARG MYSQL_CONNECTOR_VERSION=8.0.17

# add MySQL JDBC connector to server home as a third party library
ADD --chown=wso2carbon:wso2 https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar ${WSO2_SERVER_HOME}/repository/components/dropins/
```

Thus, there is no need to mount the binary via a Docker volume mount during the runtime.

Please feel free to let us know if you have further suggestions and concerns.

**Comment by chirangaalwis** [comment]
Removing this issue from the milestone [`3.2.0.1`](https://github.com/wso2/docker-apim/milestone/17) since, this is a query.

**Comment by david-maumenee** [comment]
Thanks for the answer
