### ISSUE TITLE
[2.5.0] Download product pack from Github

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-apim#362]
**Description:**
Since the GA product packs are hosted in Github, it is required to download GA product packs from the Github.

**Affected Product Version:**
2.5.0

**Sub Tasks:**
- [x] Download GA product pack from Github in Ubuntu based Docker resources
- [x] Download GA product pack from Github in Alpine based Docker resources
- [x] Download GA product pack from Github in CentOS based Docker resources
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
Fixed.
