### ISSUE TITLE
Dockerfiles 2.1.0 release doesn't have wso2am folder within the zip file

### ISSUE THREAD

**Issue by chintana** [wso2/docker-apim#40]
Downloaded release from https://github.com/wso2/docker-apim/releases. README says,

> * Build the docker image
>    - Navigate to `<DOCKERFILES_HOME>/wso2am`.

However there's no such folder. Here's what I see when I unzip this. What am I missing?

```
wso2am-dockerfile-2.1.0 # ls -la
total 28
drwxr-xr-x 3 root     root      4096 Mar 14 18:43 .
drwxr-xr-x 6 chintana chintana  4096 Mar 27 15:28 ..
drwxr-xr-x 5 root     root      4096 Mar 14 18:42 common
-rw-r--r-- 1 root     root     11357 Feb  7 13:50 LICENSE
-rw-r--r-- 1 root     root      3679 Mar 14 18:42 README.md
```

**Comment by anuruddhal** [comment]
I have attached the correct zip file to the release. In the readme file following should be changed from

Navigate to <DOCKERFILES_HOME>/wso2am. 

to

Navigate to <DOCKERFILES_HOME>/dockerfile.
