### ISSUE TITLE
PostgreSQL scripts

### ISSUE THREAD

**Issue by rsam35** [wso2/docker-apim#43]
Hello,

Will you provide a Dockerfile and SQL scripts for PostgreSQL backend ?

Thank you.

**Comment by anuruddhal** [comment]
Hi,

There is no plan to provide Dockerfile for PostgreSQL. You can find the SQL scripts for postgreSQL inside the API manager pack on  <APIM_HOME>/dbscripts folder.

**Comment by DilanUA** [comment]
Closing based on above comment.
