### ISSUE TITLE
pattern-7 User Self Registration tab missing

### ISSUE THREAD

**Issue by raviada** [wso2/docker-apim#45]
There are a few issues with this
1) Resident Identity Provider page doesn't show up. getting the following error.
```
java.io.IOException: An exception occurred processing JSP page /idpmgt/idp-mgt-edit-local.jsp at line 61
58:     ConfigurationContext configContext = (ConfigurationContext) config.getServletContext()
59:             .getAttribute(CarbonConstants.CONFIGURATION_CONTEXT);
60:     IdentityGovernanceAdminClient client = new IdentityGovernanceAdminClient(cookie, backendServerURL, configContext);
61:    Map<String, Map<String, List<ConnectorConfig>>> catMap = client.getConnectorList();
```

Got this resolved with a workaround of copying IS 5.3.0 files as mentioned here
```https://stackoverflow.com/questions/42972767/wso2-api-manager-2-1-error-when-try-to-use-resident-identity-provider/43601327```

2) Self Registration tab, Login Policies, Password Policies are not showing up
```This will deploy the following,

Mysql server (container) with apimdb, userdb, regdb
APIM Container
Nginx Load Balancer container and points the APIM components through the load balancer.
```
3) I see the above in the docker-compose page on pattern-7, ```https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-7```, but I don't see nginx container configuration in docker compose file, instead tomcat is configured with proxy pass to 80 and 443

**Comment by DilanUA** [comment]
Closing this since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
