### ISSUE TITLE
Update docker artifacts for APIM 4.1.0 release

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/docker-apim#456]
**Description:**
The following tasks should be completed with the new docker artifacts.

- [ ] Update Dockerfiles for APIM 4.1.0
- [ ] Update docker-compose scenarios for APIM 4.1.0
- [ ] Support tryout scenarios on Apple M1(arm64) based systems

**Comment by PasanT9** [comment]
[Add support for APIM 4.1.0-beta #453](https://github.com/wso2/docker-apim/pull/453)
[Add support for APIM 4.1.0-beta in apim-is-as-km-with-analytics #454](https://github.com/wso2/docker-apim/pull/454)

**Comment by PasanT9** [comment]
https://github.com/wso2/docker-apim/pull/458
https://github.com/wso2/docker-apim/pull/459
