### ISSUE TITLE
Build command for docker missing path

### ISSUE THREAD

**Issue by acroberts16** [wso2/docker-apim#463]
**Description:**

Instructions provided here:  https://github.com/wso2/docker-apim/

Need to be updated to include the path:

docker build -t wso2am:4.1.0 .

> Include the . (dot) to indicate the path.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run through build steps for ubuntu image.

**Comment by PasanT9** [comment]
Replicate of https://github.com/wso2/docker-apim/issues/462
