### ISSUE TITLE
Can not pull images from  https://docker.wso2.com

### ISSUE THREAD

**Issue by yacineslimani** [wso2/docker-apim#48]
i have this error when i try to pull images from the official docker :  

> Error response from daemon: Get https://docker.wso2.com/v2/apim-pattern4-apim_rdbms/manifests/latest: unauthorized: authentication required

I create an account in WSO2 web site http://wso2.com/ but it didn't work

**Comment by pubudu538** [comment]
You need to first login to docker.wso2.com first.

# docker login docker.wso2.com

Then you can pull the docker image as below.

# docker pull docker.wso2.com/apim-pattern4-apim_rdbms:2.1.0

Please note that the tag is 2.1.0 and not the latest.

**Comment by yacineslimani** [comment]
i tried to login in docker.wso2.com and i have the same error 

> docker login docker.wso2.com
Username: {my email address wich i use to login in wso2 web site}
Password: 
Error response from daemon: Get https://docker.wso2.com/v2/: unauthorized: authentication required

**Comment by chamilad** [comment]
You need to use the username that you use to login to WSO2 site, and not the email address. For example, if it is the same as your GitHub account it would be,

```
docker login docker.wso2.com
Username: yacineslimani@wso2.com
Password: ******
```
