### ISSUE TITLE
Can't be root on store / publisher (pattern-3)

### ISSUE THREAD

**Issue by K3vin-V** [wso2/docker-apim#51]
When launched (on Docker with compose) the container store / publisher, I can't be logged as the "root" default user
`docker exec -it pattern3_store_1 bash
wso2user@`
I tried to pass through :
`wso2user@...:/mnt$ su
su: must be run from a terminal
wso2user@...:/mnt$ sudo
bash: sudo: command not found`
Since the gateway-worker is not recognised by the store (in the API Console tab), I need to update the "/etc/hosts" file
*SSH not enabled

**Comment by pubudu538** [comment]
We are running the container as wso2user and you cannot update /etc/hosts file. I am not sure why gateway-worker is not recognized. You can update /etc/hosts file as mentioned in https://docs.docker.com/compose/compose-file/#external_links

**Comment by K3vin-V** [comment]
I tried this solution but it doesn't work.
In my browser console the error returned  is "GET https://gateway-worker:8243/pizzashack/1.0.1/menu net::ERR_NAME_NOT_RESOLVED"
Thanks for your reply
