### ISSUE TITLE
Certificate imported into keystore wso2carbon.jks is lost after container restart

### ISSUE THREAD

**Issue by ricardinhorio** [wso2/docker-apim#54]
After having my containers running, I added a certificate over carbon and after restarting the container with docker-compose restart, the certificate is lost.

How can I solve that?
How can I have the details of the image that is used as base?

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue now since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
