### ISSUE TITLE
Cannot locate dockerfiles

### ISSUE THREAD

**Issue by rwoods02** [wso2/docker-apim#57]
**Description:**
Dockerfiles for two images are not available in this repo or anywhere I searched online

pattern 3 docker.wso2.com/wso2am-analytics:2.1.0
pattern 7 docker.wso2.com/wso2is-as-keymanager:5.3.0

I am layering these two images on centos7 base layer in order to get the api manager to run in openshift.

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Centos7

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue now since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
