### ISSUE TITLE
Error in startup script for docker-compose pattern-7

### ISSUE THREAD

**Issue by wortho** [wso2/docker-apim#59]
**Description:**
Error in startup script for docker-compose pattern-7 when starting api-manager

> api-manager_1     | Starting wso2am-2.1.0 with [Startup Args] , [CARBON_HOME] /mnt/172.18.0.3/wso2am-2.1.0
> api-manager_1     | /usr/local/bin/init.sh: /mnt/172.18.0.3/wso2am-2.1.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory
> api-manager_1     | ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 126

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**
Follow the steps in the readme for [pattern-7](https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-7)

**Comment by wortho** [comment]
The problem was caused by the git config core.autocrlf true which converted the .sh to use CRLF line endings.

**Comment by DavidNorena** [comment]
Thanks man you saved my ass !
