### ISSUE TITLE
Web app does not sync in APIM docker worker nodes

### ISSUE THREAD

**Issue by mushthaq33** [wso2/docker-apim#60]
**Description:**
Web apps deployed in gateway manager node does not sync up with gateway worker node

**Steps to reproduce:**
In pattern-3 deploy a web app in gateway manager node and the web app is not seen in the gateway worker node

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue now since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
