### ISSUE TITLE
Update Docker Compose Templates to use new API-M Docker Images

### ISSUE THREAD

**Issue by imesh** [wso2/docker-apim#63]
**Description:**
Currently, API Manager Docker Compose templates use a separate set of Dockerfiles for building its Docker images. This process can be improved by using the API Manager Docker images built with the default Dockerfiles and using volume mounts to provide the configurations. As a result, Docker Compose templates would not need to build new product Docker images.

**Affected Product Version:**
2.1.0

**Related Issues:**
https://github.com/wso2/docker-is/issues/18, https://github.com/wso2/docker-ei/issues/13, https://github.com/wso2/docker-das/issues/3

**Comment by DilanUA** [comment]
Closing based on above mentioned task completions.
