### ISSUE TITLE
Simplify the docker-compose configs by removing deployment pattern representation

### ISSUE THREAD

**Issue by msmshariq** [wso2/docker-apim#70]
**Description:**

The current implementation of the docker compose configurations implement the API Manager deployment patterns. Since docker compose configurations are mainly used to tryout the products rather than implement a full-blown distributed deployment, we propose to simplify the docker compose configurations by removing the deployment pattern implementation.

Instead of implementing deployment patterns, the docker compose configurations will contain commonly used scenarios such as;

- API Manager with Analytics
- API Manager with Identity Server as Key Manager

As per this initiative, we will get rid of the pattern-* configs for docker compose and instead implement aforementioned commonly used scenarios.

**Comment by DilanUA** [comment]
Closing based on above PR being merged.
