### ISSUE TITLE
Pattern 2 : Exit with error at startup :  ..... wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by yhilem** [wso2/docker-apim#9]
.............................................................................................................................................................................
PS C:\OpenSource\INFRA\wso2\docker-apim\docker-compose\pattern-2> docker-compose logs
Attaching to pattern2_apim_rdbms_1, pattern2_api-manager_1, pattern2_am-analytics_1
api-manager_1   | Initializing wso2am-2.0.0 in default profile on default platform...
api-manager_1   | Going to sleep for 90s...
api-manager_1   | Successfully updated localMemberHost with 172.18.0.4
api-manager_1   | Creating directory /mnt/172.18.0.4
api-manager_1   | Creating symlink [Target] /mnt/wso2am-2.0.0, [Link] /mnt/172.18.0.4/wso2am-2.0.0
api-manager_1   | Copying artifacts in /mnt/wso2-artifacts to /mnt/172.18.0.4/wso2am-2.0.0
api-manager_1   | Starting wso2am-2.0.0 with [Startup Args] , [CARBON_HOME] /mnt/172.18.0.4/wso2am-2.0.0
apim_rdbms_1    | 170129 13:41:20 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
api-manager_1   | /usr/local/bin/init.sh: /mnt/172.18.0.4/wso2am-2.0.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory
apim_rdbms_1    | 170129 13:41:20 [Note] mysqld (mysqld 5.5.54) starting as process 1 ...
api-manager_1   | ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 126
apim_rdbms_1    | 170129 13:41:20 [Note] Plugin 'FEDERATED' is disabled.
apim_rdbms_1    | 170129 13:41:20 InnoDB: The InnoDB memory heap is disabled
apim_rdbms_1    | 170129 13:41:20 InnoDB: Mutexes and rw_locks use GCC atomic builtins
apim_rdbms_1    | 170129 13:41:20 InnoDB: Compressed tables use zlib 1.2.3
apim_rdbms_1    | 170129 13:41:20 InnoDB: Using Linux native AIO
apim_rdbms_1    | 170129 13:41:20 InnoDB: Initializing buffer pool, size = 128.0M
apim_rdbms_1    | 170129 13:41:20 InnoDB: Completed initialization of buffer pool
apim_rdbms_1    | 170129 13:41:20 InnoDB: highest supported file format is Barracuda.
apim_rdbms_1    | 170129 13:41:20  InnoDB: Waiting for the background threads to start
apim_rdbms_1    | 170129 13:41:21 InnoDB: 5.5.54 started; log sequence number 2846607
apim_rdbms_1    | 170129 13:41:21 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
apim_rdbms_1    | 170129 13:41:21 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
apim_rdbms_1    | 170129 13:41:21 [Note] Server socket created on IP: '0.0.0.0'.
apim_rdbms_1    | 170129 13:41:21 [Warning] 'proxies_priv' entry '@ root@616883daf044' ignored in --skip-name-resolve mode.
apim_rdbms_1    | 170129 13:41:21 [Note] Event Scheduler: Loaded 0 events
apim_rdbms_1    | 170129 13:41:21 [Note] mysqld: ready for connections.
apim_rdbms_1    | Version: '5.5.54'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)
am-analytics_1  | Initializing wso2am-analytics-2.0.0 in default profile on default platform...
am-analytics_1  | Going to sleep for 5s...
am-analytics_1  | Successfully updated localMemberHost with 172.18.0.3
am-analytics_1  | Creating directory /mnt/172.18.0.3
am-analytics_1  | Creating symlink [Target] /mnt/wso2am-analytics-2.0.0, [Link] /mnt/172.18.0.3/wso2am-analytics-2.0.0
am-analytics_1  | Copying artifacts in /mnt/wso2-artifacts to /mnt/172.18.0.3/wso2am-analytics-2.0.0
am-analytics_1  | Starting wso2am-analytics-2.0.0 with [Startup Args] , [CARBON_HOME] /mnt/172.18.0.3/wso2am-analytics-2.0.0
am-analytics_1  | /usr/local/bin/init.sh: /mnt/172.18.0.3/wso2am-analytics-2.0.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory
am-analytics_1  | ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 126
PS C:\OpenSource\INFRA\wso2\docker-apim\docker-compose\pattern-2>
.............................................................................................................................................................................

**Comment by anuruddhal** [comment]
You can't run these images on windows. You need to run it on a Linux based kernel.
If you are running on docker for windows make sure you have selected Linux kernel [1].

[1] https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by yhilem** [comment]
Thank you.
I installed DOcker CE Version 17.06.0-ce-win18 (12627) and it works.
